ignorePatterns:
  - '!testing'
ignores:
  - '@just-web/repo-scripts'
  - '@repobuddy/*'
  - '@size-limit/*'
  - '@types/jest'
  - 'jest-*'
  - repobuddy
  - rimraf # https://github.com/depcheck/depcheck/issues/776
  - size-limit
  - ts-jest
  - tslib
