ignores:
  - '@just-web/fetch'  # inferred type needs
  - '@just-web/states' # inferred type needs
  - '@repobuddy/*'
  - '@size-limit/*'
  - '@types/jest'
  - eslint*
  - 'jest-*'
  - repobuddy
  - rimraf # https://github.com/depcheck/depcheck/issues/776
  - size-limit
  - ts-jest
  - tslib
