packages:
  - apps/*/*
  - components/*
  - examples/*
  - frameworks/*
  - libraries/*
  - plugins/*
  - presets/*
  - tools/*

catalog:
  '@repobuddy/vitest': ^2.1.1

overrides:
  glob@>=10.2.0 <10.5.0: '>=10.5.0'

patchedDependencies:
  '@changesets/assemble-release-plan': patches/@changesets__assemble-release-plan.patch
