ignores:
  - '@repobuddy/*'
  - '@size-limit/*'
  - '@types/jest'
  - '@typescript-eslint/parser'
  - eslint-plugin-storybook
  - npm-check-updates
  - rimraf # https://github.com/depcheck/depcheck/issues/776
  - size-limit
  - tslib
