ignorePatterns:
  - '!testing'
ignores:
  - '@just-web/repo-scripts'
  - '@repobuddy/jest'
  - '@size-limit/*'
  - '@types/jest'
  - 'jest-*'
  - size-limit
  - type-plus # used in `testing` exports
  - ts-jest
