ignores:
  - "@babel/plugin-syntax-flow"
  - "@babel/plugin-transform-react-jsx"
  - "@just-web/repo-scripts"
  - "@storybook/*"
  - "@testing-library/*"
  - "@size-limit/*"
  - "@types/jest"
  - "@types/node"
  - "@types/platform"
  - "@typescript-eslint/parser"
  - autoprefixer
  - babel-loader
  - css-loader
  - identity-obj-proxy
  - jest-validate
  - jest-watch-suspend
  - jest-watch-toggle-config
  - jest-watch-typeahead
  - npm-check-updates
  - postcss
  - react-refresh
  - size-limit
  - storybook-dark-mode
  - storybook-css-modules-preset
  - style-loader
  - ts-jest
  - webpack
