name: nodejs
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
jobs:
  verify:
    uses: unional/.github/.github/workflows/web-rush-verify.yml@main
    secrets:
      codacy-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
  release:
    if: github.ref == 'refs/heads/main'
    uses: unional/.github/.github/workflows/rush-release.yml@main
    needs: verify
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
  # docgen:
  #   if: github.ref == 'refs/heads/main'
  #   uses: unional/.github/.github/workflows/build-docs.yml@main
  #   needs: release
