name: pull-request
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code:
    uses: justland/.github/.github/workflows/pnpm-verify.yml@main
    with:
      node-version: '[16, 18]'
      pnpm-version: 8.2.0
